// // constants/equipment/equipmentIcons.ts
// import type { ImageSourcePropType } from "react-native";

// export const equipmentIcons: Record<string, ImageSourcePropType> = {
//   // MACHINES
//   ab_crunch_machine: require("@/assets/equipment/ab_crunch_machine.png"),
//   abductor_machine: require("@/assets/equipment/abductor_machine.png"),
//   adductor_machine: require("@/assets/equipment/adductor_machine.png"),
//   assisted_weight_machine: require("@/assets/equipment/assisted_weight_machine.png"),
//   bench_press_machine: require("@/assets/equipment/bench_press_machine.png"),
//   bicep_curl_machine: require("@/assets/equipment/bicep_curl_machine.png"),
//   calf_raise_machine: require("@/assets/equipment/calf_raise_machine.png"),
//   calf_extension_machine: require("@/assets/equipment/calf_extension_machine.png"),
//   fly_machine: require("@/assets/equipment/fly_machine.png"),
//   glute_machine: require("@/assets/equipment/glute_machine.png"),
//   hack_squat_machine_selectorized: require("@/assets/equipment/hack_squat_machine_selectorized.png"),
//   leg_curl_machine: require("@/assets/equipment/leg_curl_machine.png"),
//   leg_extension_machine: require("@/assets/equipment/leg_extension_machine.png"),
//   leg_press_machine_selectorized: require("@/assets/equipment/leg_press_machine_selectorized.png"),
//   multi_hip_machine: require("@/assets/equipment/multi_hip_machine.png"),
//   overhead_press_machine: require("@/assets/equipment/overhead_press_machine.png"),
//   preacher_curl_machine: require("@/assets/equipment/preacher_curl_machine.png"),
//   row_machine: require("@/assets/equipment/row_machine.png"),
//   seated_leg_curl_machine: require("@/assets/equipment/seated_leg_curl_machine.png"),
//   sissy_squat_machine: require("@/assets/equipment/sissy_squat_machine.png"),
//   torso_rotation_machine: require("@/assets/equipment/torso_rotation_machine.png"),
//   tricep_dip_machine: require("@/assets/equipment/tricep_dip_machine.png"),
//   triceps_extension_machine: require("@/assets/equipment/triceps_extension_machine.png"),
//   lateral_raise_machine: require("@/assets/equipment/lateral_raise_machine.png"),
//   bent_arm_fly_machine: require("@/assets/equipment/bent_arm_fly_machine.png"),
//   back_extension_machine: require("@/assets/equipment/back_extension_machine.png"),
//   smith_machine: require("@/assets/equipment/smith_machine.png"),

//   // PLATE-LOADED
//   plate_loaded_t_bar: require("@/assets/equipment/plate_loaded_t_bar.png"),
//   plate_loaded_lat_pulldown: require("@/assets/equipment/plate_loaded_lat_pulldown.png"),
//   plate_loaded_chest_horizontal: require("@/assets/equipment/plate_loaded_chest_horizontal.png"),
//   plate_loaded_preacher: require("@/assets/equipment/plate_loaded_preacher.png"),
//   plate_loaded_seated_calf: require("@/assets/equipment/plate_loaded_seated_calf.png"),
//   plate_loaded_glute: require("@/assets/equipment/plate_loaded_glute.png"),
//   plate_loaded_hip_thrust: require("@/assets/equipment/plate_loaded_hip_thrust.png"),
//   plate_loaded_hip_thrust_belt: require("@/assets/equipment/plate_loaded_hip_thrust_belt.png"),
//   plate_loaded_chest_supported_t_bar: require("@/assets/equipment/plate_loaded_chest_supported_t_bar.png"),
//   plate_loaded_ab_crunch: require("@/assets/equipment/plate_loaded_ab_crunch.png"),
//   plate_loaded_chest_supported_row: require("@/assets/equipment/plate_loaded_chest_supported_row.png"),
//   plate_loaded_standing_lateral_raise: require("@/assets/equipment/plate_loaded_standing_lateral_raise.png"),
//   plate_loaded_pullover: require("@/assets/equipment/plate_loaded_pullover.png"),
//   plate_loaded_standing_leg_curl: require("@/assets/equipment/plate_loaded_standing_leg_curl.png"),
//   plate_loaded_dip_machine: require("@/assets/equipment/plate_loaded_dip_machine.png"),
//   plate_loaded_angled_calf_press: require("@/assets/equipment/plate_loaded_angled_calf_press.png"),
//   pendulum_squat_machine: require("@/assets/equipment/pendulum_squat_machine.png"),
//   vertical_leg_press: require("@/assets/equipment/vertical_leg_press.png"),
//   belt_squat_machine: require("@/assets/equipment/belt_squat_machine.png"),
//   plate_loaded_iso_lateral_chest: require("@/assets/equipment/plate_loaded_iso_lateral_chest.png"),
//   plate_loaded_decline_chest: require("@/assets/equipment/plate_loaded_decline_chest.png"),
//   plate_loaded_high_row: require("@/assets/equipment/plate_loaded_high_row.png"),
//   plate_loaded_incline_chest: require("@/assets/equipment/plate_loaded_incline_chest.png"),
//   plate_loaded_iso_lateral_row: require("@/assets/equipment/plate_loaded_iso_lateral_row.png"),
//   plate_loaded_shrug_machine: require("@/assets/equipment/plate_loaded_shrug_machine.png"),
//   plate_loaded_shoulder_machine: require("@/assets/equipment/plate_loaded_shoulder_machine.png"),
//   leg_press_plate_loaded: require("@/assets/equipment/leg_press_plate_loaded.png"),
//   plate_loaded_hack_squat: require("@/assets/equipment/plate_loaded_hack_squat.png"),

//   // BENCHES & RACKS
//   back_extension_bench: require("@/assets/equipment/back_extension_bench.png"),
//   decline_bench: require("@/assets/equipment/decline_bench.png"),
//   dip_bar: require("@/assets/equipment/dip_bar.png"),
//   flat_bench: require("@/assets/equipment/flat_bench.png"),
//   glute_ham_raise_bench: require("@/assets/equipment/glute_ham_raise_bench.png"),
//   incline_bench: require("@/assets/equipment/incline_bench.png"),
//   preacher_curl_bench: require("@/assets/equipment/preacher_curl_bench.png"),
//   pull_up_bar: require("@/assets/equipment/pull_up_bar.png"),
//   squat_rack: require("@/assets/equipment/squat_rack.png"),
//   vertical_bench: require("@/assets/equipment/vertical_bench.png"),

//   // CABLES
//   crossover_cable: require("@/assets/equipment/crossover_cable.png"),
//   hi_lo_pull_cable: require("@/assets/equipment/hi_lo_pull_cable.png"),
//   lat_pulldown_cable: require("@/assets/equipment/lat_pulldown_cable.png"),
//   row_cable: require("@/assets/equipment/row_cable.png"),

//   // FREE WEIGHTS
//   olympic_barbell: require("@/assets/equipment/olympic_barbell.png"),
//   ez_bar: require("@/assets/equipment/ez_bar.png"),
//   landmine: require("@/assets/equipment/landmine.png"),
//   plates: require("@/assets/equipment/plates.png"),
//   trap_bar: require("@/assets/equipment/trap_bar.png"),
//   short_bar: require("@/assets/equipment/short_bar.png"),
//   dumbbells: require("@/assets/equipment/dumbbells.png"),
//   kettlebells: require("@/assets/equipment/kettlebells.png"),

//   // FUNCTIONAL
//   ab_wheel: require("@/assets/equipment/ab_wheel.png"),
//   plyo_box: require("@/assets/equipment/plyo_box.png"),
//   medicine_ball: require("@/assets/equipment/medicine_ball.png"),
//   stability_ball: require("@/assets/equipment/stability_ball.png"),
//   tire: require("@/assets/equipment/tire.png"),
//   trx: require("@/assets/equipment/trx.png"),
//   foam_roller: require("@/assets/equipment/foam_roller.png"),
//   sled: require("@/assets/equipment/sled.png"),
//   battle_ropes: require("@/assets/equipment/battle_ropes.png"),

//   // BANDS & ACCESSORIES
//   loop_bands: require("@/assets/equipment/loop_bands.png"),
//   mini_bands: require("@/assets/equipment/mini_bands.png"),
//   skipping_rope: require("@/assets/equipment/skipping_rope.png"),

//   // CARDIO
//   air_bike: require("@/assets/equipment/air_bike.png"),
//   stationary_bike: require("@/assets/equipment/stationary_bike.png"),
//   elliptical: require("@/assets/equipment/elliptical.png"),
//   rowing_machine_cardio: require("@/assets/equipment/rowing_machine_cardio.png"),
//   stair_stepper: require("@/assets/equipment/stair_stepper.png"),
//   treadmill: require("@/assets/equipment/treadmill.png"),
//   vertical_climber: require("@/assets/equipment/vertical_climber.png"),
//   ski_erg: require("@/assets/equipment/ski_erg.png"),
// };
